import { appState } from '../state.js';
import { closeModal, emptyState, objectFromForm, openModal, pageHeader } from '../ui.js';
import { generateId, safeText, todayISO } from '../utils.js';
import { removeItem, simpleCard, upsert } from './shared.js';

export function renderReviews(){ const actions='<button class="btn primary" data-action="open-review-modal" data-type="daily">مراجعة يومية</button><button class="btn ghost" data-action="open-review-modal" data-type="weekly">مراجعة أسبوعية</button>'; return `<section class="page">${pageHeader('المراجعات','راجع اليوم والأسبوع حتى يتحسن النظام فعليًا.',actions)}<div class="grid grid-2">${appState.data.reviews.length?appState.data.reviews.map(card).join(''):emptyState('لا توجد مراجعات','اكتب مراجعة يومية قصيرة أو مراجعة أسبوعية كاملة.',actions)}</div></section>`; }
function card(item){ return simpleCard('review', item, `<p>${safeText(item.lesson || item.weekLearned || 'بدون درس')}</p><div class="meta"><span>${safeText(item.type)}</span><span>${safeText(item.date)}</span><span>تركيز: ${safeText(item.focusScore||'-')}/10</span><span>طاقة: ${safeText(item.energyScore||'-')}/10</span></div>`); }
export function openReviewModal(id='', type='daily'){ const item=appState.data.reviews.find(x=>x.id===id)||{type:type==='weekly'?'أسبوعية':'يومية',date:todayISO()}; openModal({title:item.id?'تعديل مراجعة':'إضافة مراجعة',saveText:'حفظ',body:form(item),onSave:saveReview}); }
function form(item){ const weekly=item.type==='أسبوعية'; return `<form id="entityForm" class="form-grid"><input type="hidden" name="id" value="${safeText(item.id||'')}"><label>النوع<select name="type"><option ${item.type==='يومية'?'selected':''}>يومية</option><option ${item.type==='أسبوعية'?'selected':''}>أسبوعية</option></select></label><label>التاريخ<input type="date" name="date" value="${safeText(item.date||todayISO())}"></label>
${weekly?`<label class="full">أهم إنجازات الأسبوع<textarea name="weekWins">${safeText(item.weekWins||'')}</textarea></label><label class="full">أهم مشاكل الأسبوع<textarea name="weekProblems">${safeText(item.weekProblems||'')}</textarea></label><label class="full">ماذا تعلمت؟<textarea name="weekLearned">${safeText(item.weekLearned||'')}</textarea></label><label>أفضل مشروع<input name="bestProject" value="${safeText(item.bestProject||'')}"></label><label>مشروع يحتاج إنقاذ<input name="rescueProject" value="${safeText(item.rescueProject||'')}"></label><label class="full">أوقف / أبدأ / أستمر<textarea name="startStopContinue">${safeText(item.startStopContinue||'')}</textarea></label>`:`<label class="full">إنجازات اليوم<textarea name="achievements">${safeText(item.achievements||'')}</textarea></label><label class="full">ما الذي عطّلني؟<textarea name="blockers">${safeText(item.blockers||'')}</textarea></label><label class="full">أهم درس<textarea name="lesson">${safeText(item.lesson||'')}</textarea></label><label class="full">أهم إجراء غدًا<textarea name="tomorrowAction">${safeText(item.tomorrowAction||'')}</textarea></label><label>تقييم التركيز<input type="number" min="1" max="10" name="focusScore" value="${safeText(item.focusScore||5)}"></label><label>تقييم الطاقة<input type="number" min="1" max="10" name="energyScore" value="${safeText(item.energyScore||5)}"></label>`}</form>`; }
function saveReview(){ const formEl=document.getElementById('entityForm'); const d=objectFromForm(formEl); upsert('reviews',{...d,id:d.id||generateId('review'),title:`مراجعة ${d.type} - ${d.date}`}); closeModal(); }
export function editReview(id){ openReviewModal(id); }
export function deleteReview(id){ removeItem('reviews',id); }
